branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Enable building pull requests.
    - master
language: java
sudo: false
jdk:
  - oraclejdk8
os:
  - linux
cache:
 directories:
   - $HOME/.m2
install: true
before_install:
  - sudo apt-get install -y protobuf-compiler
script:
  - mvn package -Pdist -DskipTests=true -Dtar
