// Code generated by protoc-gen-go.
// source: proxy.proto
// DO NOT EDIT!

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	BlockMeta
	BlockStorageNode
	BlockStorage
	INodeID
	INodeMeta
	INodeFileBlock
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockMeta struct {
	Id               *int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Generation       *int64  `protobuf:"varint,2,opt,name=generation" json:"generation,omitempty"`
	NumberBytes      *int64  `protobuf:"varint,3,opt,name=number_bytes" json:"number_bytes,omitempty"`
	Replication      *int32  `protobuf:"varint,4,opt,name=replication" json:"replication,omitempty"`
	CollectionId     *int64  `protobuf:"varint,5,opt,name=collection_id" json:"collection_id,omitempty"`
	BlockPoolId      *string `protobuf:"bytes,6,opt,name=block_pool_id" json:"block_pool_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockMeta) Reset()                    { *m = BlockMeta{} }
func (m *BlockMeta) String() string            { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()               {}
func (*BlockMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockMeta) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BlockMeta) GetGeneration() int64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *BlockMeta) GetNumberBytes() int64 {
	if m != nil && m.NumberBytes != nil {
		return *m.NumberBytes
	}
	return 0
}

func (m *BlockMeta) GetReplication() int32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *BlockMeta) GetCollectionId() int64 {
	if m != nil && m.CollectionId != nil {
		return *m.CollectionId
	}
	return 0
}

func (m *BlockMeta) GetBlockPoolId() string {
	if m != nil && m.BlockPoolId != nil {
		return *m.BlockPoolId
	}
	return ""
}

type BlockStorageNode struct {
	DataNodeId       *string `protobuf:"bytes,1,req,name=data_node_id" json:"data_node_id,omitempty"`
	StorageId        *string `protobuf:"bytes,2,req,name=storage_id" json:"storage_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlockStorageNode) Reset()                    { *m = BlockStorageNode{} }
func (m *BlockStorageNode) String() string            { return proto.CompactTextString(m) }
func (*BlockStorageNode) ProtoMessage()               {}
func (*BlockStorageNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockStorageNode) GetDataNodeId() string {
	if m != nil && m.DataNodeId != nil {
		return *m.DataNodeId
	}
	return ""
}

func (m *BlockStorageNode) GetStorageId() string {
	if m != nil && m.StorageId != nil {
		return *m.StorageId
	}
	return ""
}

type BlockStorage struct {
	Nodes            []*BlockStorageNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	Id               *int64              `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BlockStorage) Reset()                    { *m = BlockStorage{} }
func (m *BlockStorage) String() string            { return proto.CompactTextString(m) }
func (*BlockStorage) ProtoMessage()               {}
func (*BlockStorage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BlockStorage) GetNodes() []*BlockStorageNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *BlockStorage) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type INodeID struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *INodeID) Reset()                    { *m = INodeID{} }
func (m *INodeID) String() string            { return proto.CompactTextString(m) }
func (*INodeID) ProtoMessage()               {}
func (*INodeID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *INodeID) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type INodeMeta struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Permission       *int64  `protobuf:"varint,3,req,name=permission" json:"permission,omitempty"`
	ModificationTime *int64  `protobuf:"varint,4,req,name=modification_time" json:"modification_time,omitempty"`
	AccessTime       *int64  `protobuf:"varint,5,req,name=access_time" json:"access_time,omitempty"`
	Header           *int64  `protobuf:"varint,6,opt,name=header" json:"header,omitempty"`
	Type             *int32  `protobuf:"varint,7,req,name=type" json:"type,omitempty"`
	ParentId         *int64  `protobuf:"varint,8,opt,name=parent_id" json:"parent_id,omitempty"`
	ClientName       *string `protobuf:"bytes,9,opt,name=client_name" json:"client_name,omitempty"`
	ClientMachine    *string `protobuf:"bytes,10,opt,name=client_machine" json:"client_machine,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *INodeMeta) Reset()                    { *m = INodeMeta{} }
func (m *INodeMeta) String() string            { return proto.CompactTextString(m) }
func (*INodeMeta) ProtoMessage()               {}
func (*INodeMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *INodeMeta) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *INodeMeta) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *INodeMeta) GetPermission() int64 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *INodeMeta) GetModificationTime() int64 {
	if m != nil && m.ModificationTime != nil {
		return *m.ModificationTime
	}
	return 0
}

func (m *INodeMeta) GetAccessTime() int64 {
	if m != nil && m.AccessTime != nil {
		return *m.AccessTime
	}
	return 0
}

func (m *INodeMeta) GetHeader() int64 {
	if m != nil && m.Header != nil {
		return *m.Header
	}
	return 0
}

func (m *INodeMeta) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *INodeMeta) GetParentId() int64 {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return 0
}

func (m *INodeMeta) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *INodeMeta) GetClientMachine() string {
	if m != nil && m.ClientMachine != nil {
		return *m.ClientMachine
	}
	return ""
}

type INodeFileBlock struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	NextBlockId      *int64 `protobuf:"varint,2,opt,name=next_block_id" json:"next_block_id,omitempty"`
	NumberBytes      *int64 `protobuf:"varint,3,opt,name=number_bytes" json:"number_bytes,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *INodeFileBlock) Reset()                    { *m = INodeFileBlock{} }
func (m *INodeFileBlock) String() string            { return proto.CompactTextString(m) }
func (*INodeFileBlock) ProtoMessage()               {}
func (*INodeFileBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *INodeFileBlock) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *INodeFileBlock) GetNextBlockId() int64 {
	if m != nil && m.NextBlockId != nil {
		return *m.NextBlockId
	}
	return 0
}

func (m *INodeFileBlock) GetNumberBytes() int64 {
	if m != nil && m.NumberBytes != nil {
		return *m.NumberBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockMeta)(nil), "proxy.BlockMeta")
	proto.RegisterType((*BlockStorageNode)(nil), "proxy.BlockStorageNode")
	proto.RegisterType((*BlockStorage)(nil), "proxy.BlockStorage")
	proto.RegisterType((*INodeID)(nil), "proxy.INodeID")
	proto.RegisterType((*INodeMeta)(nil), "proxy.INodeMeta")
	proto.RegisterType((*INodeFileBlock)(nil), "proxy.INodeFileBlock")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0x21, 0xc9, 0xb2, 0xab, 0x93, 0x6d, 0xd4, 0x74, 0xd5, 0xb2, 0x9b, 0xa0, 0xa1, 0xe0,
	0xe4, 0xa1, 0x73, 0x27, 0xa3, 0x28, 0xe0, 0xa1, 0x59, 0xf2, 0x00, 0x02, 0x4d, 0x5d, 0x6c, 0x22,
	0x12, 0x29, 0x50, 0x0c, 0x60, 0xef, 0x79, 0xb7, 0xbc, 0x56, 0xc0, 0x93, 0x1d, 0xc4, 0x48, 0x46,
	0x7d, 0x3a, 0xe2, 0xfe, 0xff, 0x3b, 0xc8, 0x7b, 0x67, 0x4f, 0xe7, 0x4d, 0xef, 0xac, 0xb7, 0x2c,
	0xa5, 0x8f, 0xea, 0x39, 0x82, 0x6c, 0xdb, 0x5a, 0xf5, 0xf8, 0x1f, 0xbd, 0x64, 0x00, 0xb1, 0x6e,
	0x78, 0x54, 0x46, 0x22, 0x61, 0x0c, 0xe0, 0x80, 0x06, 0x9d, 0xf4, 0xda, 0x1a, 0x1e, 0x13, 0xfb,
	0x06, 0x73, 0xf3, 0xd4, 0xed, 0xd1, 0xd5, 0xfb, 0xb3, 0xc7, 0x81, 0x27, 0x44, 0xd7, 0x90, 0x3b,
	0xec, 0x5b, 0xad, 0xc6, 0xd1, 0x49, 0x19, 0x89, 0x94, 0x15, 0xb0, 0x50, 0xb6, 0x6d, 0x51, 0x05,
	0x56, 0xeb, 0x86, 0xa7, 0x34, 0x5b, 0xc0, 0x62, 0x1f, 0xd6, 0xd5, 0xbd, 0xb5, 0x6d, 0xc0, 0xd3,
	0x32, 0x12, 0x59, 0xf5, 0x07, 0xbe, 0x52, 0x8a, 0x7b, 0x6f, 0x9d, 0x3c, 0xe0, 0x9d, 0x6d, 0x30,
	0x2c, 0x6b, 0xa4, 0x97, 0xb5, 0xb1, 0x0d, 0xd6, 0x14, 0x2b, 0x16, 0x59, 0x88, 0x35, 0x8c, 0x43,
	0x81, 0xc5, 0x81, 0x55, 0x5b, 0x98, 0xbf, 0x7f, 0xcd, 0x7e, 0x41, 0x1a, 0x1e, 0x0d, 0x3c, 0x2a,
	0x13, 0x91, 0xff, 0xfe, 0xb1, 0x19, 0x8b, 0x7f, 0xd8, 0x30, 0xd6, 0xa5, 0x6a, 0x55, 0x01, 0xb3,
	0x5d, 0x80, 0xbb, 0xbf, 0x6f, 0x16, 0x62, 0x91, 0x54, 0x2f, 0x11, 0x64, 0xc4, 0x6f, 0xfc, 0xc4,
	0x22, 0x61, 0x73, 0x98, 0x18, 0xd9, 0xe1, 0x18, 0x21, 0xc4, 0xea, 0xd1, 0x75, 0x7a, 0x18, 0x82,
	0x82, 0x84, 0x26, 0x7e, 0xc2, 0xaa, 0xb3, 0x8d, 0x7e, 0xb8, 0x88, 0xa9, 0xbd, 0xee, 0x90, 0x4f,
	0xe8, 0xd7, 0x1a, 0x72, 0xa9, 0x14, 0x0e, 0xc3, 0x08, 0x53, 0x82, 0x4b, 0x98, 0x1e, 0x51, 0x36,
	0xe8, 0x48, 0x0a, 0x6d, 0xf0, 0xe7, 0x1e, 0xf9, 0xac, 0x8c, 0x45, 0xca, 0x56, 0x90, 0xf5, 0xd2,
	0xa1, 0xf1, 0xa1, 0xf7, 0x97, 0xab, 0x78, 0xd5, 0xea, 0x80, 0x28, 0x49, 0x16, 0x54, 0xb2, 0xef,
	0xb0, 0xbc, 0xc0, 0x4e, 0xaa, 0xa3, 0x36, 0xc8, 0x81, 0x14, 0xef, 0x60, 0x49, 0x45, 0xfe, 0xe9,
	0x16, 0xc9, 0xc4, 0x4d, 0x9b, 0x02, 0x16, 0x06, 0x4f, 0xbe, 0x1e, 0x8f, 0x73, 0xb5, 0xf2, 0xf9,
	0xc1, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0e, 0x36, 0xd1, 0x49, 0x02, 0x00, 0x00,
}
