// Code generated by protoc-gen-go.
// source: proxy.proto
// DO NOT EDIT!

/*
Package proxy is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	BlockMeta
	BlockStorageNode
	BlockStorage
	INodeMeta
*/
package proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockMeta struct {
	Id           int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Generation   int64 `protobuf:"varint,2,opt,name=generation" json:"generation,omitempty"`
	NumberBytes  int64 `protobuf:"varint,3,opt,name=number_bytes,json=numberBytes" json:"number_bytes,omitempty"`
	Replication  int32 `protobuf:"varint,4,opt,name=replication" json:"replication,omitempty"`
	CollectionId int64 `protobuf:"varint,5,opt,name=collection_id,json=collectionId" json:"collection_id,omitempty"`
}

func (m *BlockMeta) Reset()                    { *m = BlockMeta{} }
func (m *BlockMeta) String() string            { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()               {}
func (*BlockMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockMeta) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockMeta) GetGeneration() int64 {
	if m != nil {
		return m.Generation
	}
	return 0
}

func (m *BlockMeta) GetNumberBytes() int64 {
	if m != nil {
		return m.NumberBytes
	}
	return 0
}

func (m *BlockMeta) GetReplication() int32 {
	if m != nil {
		return m.Replication
	}
	return 0
}

func (m *BlockMeta) GetCollectionId() int64 {
	if m != nil {
		return m.CollectionId
	}
	return 0
}

type BlockStorageNode struct {
	DataNodeId string `protobuf:"bytes,1,opt,name=data_node_id,json=dataNodeId" json:"data_node_id,omitempty"`
	StorageId  string `protobuf:"bytes,2,opt,name=storage_id,json=storageId" json:"storage_id,omitempty"`
}

func (m *BlockStorageNode) Reset()                    { *m = BlockStorageNode{} }
func (m *BlockStorageNode) String() string            { return proto.CompactTextString(m) }
func (*BlockStorageNode) ProtoMessage()               {}
func (*BlockStorageNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockStorageNode) GetDataNodeId() string {
	if m != nil {
		return m.DataNodeId
	}
	return ""
}

func (m *BlockStorageNode) GetStorageId() string {
	if m != nil {
		return m.StorageId
	}
	return ""
}

type BlockStorage struct {
	Nodes []*BlockStorageNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *BlockStorage) Reset()                    { *m = BlockStorage{} }
func (m *BlockStorage) String() string            { return proto.CompactTextString(m) }
func (*BlockStorage) ProtoMessage()               {}
func (*BlockStorage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BlockStorage) GetNodes() []*BlockStorageNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type INodeMeta struct {
	Id               int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Permission       int64  `protobuf:"varint,3,opt,name=permission" json:"permission,omitempty"`
	ModificationTime int64  `protobuf:"varint,4,opt,name=modification_time,json=modificationTime" json:"modification_time,omitempty"`
	AccessTime       int64  `protobuf:"varint,5,opt,name=access_time,json=accessTime" json:"access_time,omitempty"`
	Header           int64  `protobuf:"varint,6,opt,name=header" json:"header,omitempty"`
	Type             int32  `protobuf:"varint,7,opt,name=type" json:"type,omitempty"`
	ParentId         int64  `protobuf:"varint,8,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
}

func (m *INodeMeta) Reset()                    { *m = INodeMeta{} }
func (m *INodeMeta) String() string            { return proto.CompactTextString(m) }
func (*INodeMeta) ProtoMessage()               {}
func (*INodeMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *INodeMeta) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *INodeMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *INodeMeta) GetPermission() int64 {
	if m != nil {
		return m.Permission
	}
	return 0
}

func (m *INodeMeta) GetModificationTime() int64 {
	if m != nil {
		return m.ModificationTime
	}
	return 0
}

func (m *INodeMeta) GetAccessTime() int64 {
	if m != nil {
		return m.AccessTime
	}
	return 0
}

func (m *INodeMeta) GetHeader() int64 {
	if m != nil {
		return m.Header
	}
	return 0
}

func (m *INodeMeta) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *INodeMeta) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockMeta)(nil), "proxy.BlockMeta")
	proto.RegisterType((*BlockStorageNode)(nil), "proxy.BlockStorageNode")
	proto.RegisterType((*BlockStorage)(nil), "proxy.BlockStorage")
	proto.RegisterType((*INodeMeta)(nil), "proxy.INodeMeta")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xb4, 0x30,
	0x10, 0xc7, 0x03, 0x2c, 0xfb, 0x2d, 0x03, 0x9f, 0x59, 0x7b, 0x50, 0x12, 0xa3, 0x22, 0x5e, 0x36,
	0x31, 0xee, 0x41, 0xcf, 0x5e, 0xf6, 0xc6, 0x41, 0x0f, 0xac, 0x77, 0xd2, 0xa5, 0xe3, 0xda, 0x08,
	0x94, 0x94, 0x9a, 0xb8, 0x0f, 0xe4, 0xab, 0xf9, 0x1c, 0xa6, 0x53, 0x12, 0x89, 0xf1, 0xd6, 0xf9,
	0xcd, 0x9f, 0xe9, 0xe4, 0x47, 0x21, 0xee, 0xb5, 0xfa, 0x38, 0xac, 0x7b, 0xad, 0x8c, 0x62, 0x21,
	0x15, 0xf9, 0xa7, 0x07, 0xd1, 0xa6, 0x51, 0xf5, 0xdb, 0x23, 0x1a, 0xce, 0x8e, 0xc0, 0x97, 0x22,
	0xf5, 0x32, 0x6f, 0x15, 0x94, 0xbe, 0x14, 0xec, 0x02, 0x60, 0x8f, 0x1d, 0x6a, 0x6e, 0xa4, 0xea,
	0x52, 0x9f, 0xf8, 0x84, 0xb0, 0x2b, 0x48, 0xba, 0xf7, 0x76, 0x87, 0xba, 0xda, 0x1d, 0x0c, 0x0e,
	0x69, 0x40, 0x89, 0xd8, 0xb1, 0x8d, 0x45, 0x2c, 0x83, 0x58, 0x63, 0xdf, 0xc8, 0xda, 0xcd, 0x98,
	0x65, 0xde, 0x2a, 0x2c, 0xa7, 0x88, 0x5d, 0xc3, 0xff, 0x5a, 0x35, 0x0d, 0xd6, 0xb6, 0xaa, 0xa4,
	0x48, 0x43, 0x9a, 0x92, 0xfc, 0xc0, 0x42, 0xe4, 0x5b, 0x58, 0xd2, 0x9a, 0x5b, 0xa3, 0x34, 0xdf,
	0xe3, 0x93, 0x12, 0xc8, 0x32, 0x48, 0x04, 0x37, 0xbc, 0xea, 0x94, 0xc0, 0x6a, 0xdc, 0x3b, 0x2a,
	0xc1, 0x32, 0xdb, 0x2f, 0x04, 0x3b, 0x07, 0x18, 0xdc, 0x07, 0xb6, 0xef, 0x53, 0x3f, 0x1a, 0x49,
	0x21, 0xf2, 0x07, 0x48, 0xa6, 0x43, 0xd9, 0x2d, 0x84, 0x76, 0xd6, 0x90, 0x7a, 0x59, 0xb0, 0x8a,
	0xef, 0x4e, 0xd7, 0x4e, 0xd8, 0xef, 0x8b, 0x4b, 0x97, 0xca, 0xbf, 0x3c, 0x88, 0x0a, 0x0b, 0xfe,
	0x74, 0xc7, 0x60, 0xd6, 0xf1, 0x16, 0xc7, 0x5b, 0xe9, 0x6c, 0x7d, 0xf6, 0xa8, 0x5b, 0x39, 0x0c,
	0xd6, 0x85, 0xb3, 0x35, 0x21, 0xec, 0x06, 0x8e, 0x5b, 0x25, 0xe4, 0xcb, 0xa8, 0xa6, 0x32, 0xb2,
	0x45, 0x52, 0x16, 0x94, 0xcb, 0x69, 0xe3, 0x59, 0xb6, 0xc8, 0x2e, 0x21, 0xe6, 0x75, 0x8d, 0xc3,
	0xe0, 0x62, 0xce, 0x1a, 0x38, 0x44, 0x81, 0x13, 0x98, 0xbf, 0x22, 0x17, 0xa8, 0xd3, 0x39, 0xf5,
	0xc6, 0xca, 0x6e, 0x66, 0x0e, 0x3d, 0xa6, 0xff, 0xe8, 0x5f, 0xd0, 0x99, 0x9d, 0x41, 0xd4, 0x73,
	0x8d, 0x9d, 0xb1, 0xa2, 0x16, 0x14, 0x5f, 0x38, 0x50, 0x88, 0xdd, 0x9c, 0x9e, 0xcc, 0xfd, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x1b, 0x64, 0x34, 0x41, 0x02, 0x00, 0x00,
}
